2024-06-03 22:31:05.764605: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-03 22:31:08.033812: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-03 22:31:08.134052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22455 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:21:00.0, compute capability: 8.6
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
Model: "two_tapes_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 encoder_block (EncoderBlock  multiple                 1464960   
 )                                                               
                                                                 
 dense_regression (DenseRegr  multiple                 74753     
 ession)                                                         
                                                                 
 dense_regression_1 (DenseRe  multiple                 74753     
 gression)                                                       
                                                                 
=================================================================
Total params: 1,614,470
Trainable params: 1,610,370
Non-trainable params: 4,100
_________________________________________________________________
2024-06-03 22:31:13.602376: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8907
2024-06-03 22:31:13.709584: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2024-06-03 22:31:13.712450: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
2024-06-03 22:31:13.712516: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:237] Used ptxas at ptxas
2024-06-03 22:31:13.712646: W tensorflow/compiler/xla/stream_executor/gpu/redzone_allocator.cc:318] UNIMPLEMENTED: ptxas ptxas too old. Falling back to the driver to compile.
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2024-06-03 22:31:14.133543: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2024-06-03 22:31:14.162706: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x7f2fb8fbc260 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-06-03 22:31:14.162774: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 3090, Compute Capability 8.6
2024-06-03 22:31:14.167887: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-06-03 22:31:14.253628: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2024-06-03 22:31:14.258876: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2024-06-03 22:31:14.335083: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2024-06-03 22:31:14.654658: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2024-06-03 22:31:14.897048: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2024-06-03 22:31:15.774164: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2024-06-03 22:31:16.021178: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:absl:Found untraced functions such as _update_step_xla, dense_block_layer_call_fn, dense_block_layer_call_and_return_conditional_losses, dense_block_1_layer_call_fn, dense_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 95). These functions will not be directly callable after loading.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2024-06-04 01:45:41.072311: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:105 : INVALID_ARGUMENT: Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead.
2024-06-04 01:45:41.072437: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at strided_slice_op.cc:105 : INVALID_ARGUMENT: Expected begin, end, and strides to be 1D equal size tensors, but got shapes [3], [1], and [1] instead.
2024-06-04 01:45:41.074471: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [3], [1], and [1] instead. [Op:StridedSlice] name: strided_slice/
Traceback (most recent call last):

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1039, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 150, in __call__
    out_data = self.step(start, stop, ev_starts)

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 112, in step
    mask = tf.where(tf.not_equal(data[:,:,1:2], self.norm_zeros[1:2]), 1., 0.)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [3], [1], and [1] instead. [Op:StridedSlice] name: strided_slice/


2024-06-04 01:45:41.074524: W tensorflow/core/framework/op_kernel.cc:1818] UNKNOWN: InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead. [Op:StridedSlice] name: strided_slice/
Traceback (most recent call last):

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1039, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 150, in __call__
    out_data = self.step(start, stop, ev_starts)

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 110, in step
    data = tf.RaggedTensor.from_row_starts(values=data, row_starts=ev_starts[0:-1] - ev_starts[0])

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead. [Op:StridedSlice] name: strided_slice/


None
Steps per epoch: 19531
Traceback (most recent call last):
  File "/home/albert/Baikal/NuEnergy/start_experiment.py", line 17, in <module>
    model, history = launch_exp(EXPERIMENT_NAME, 
  File "/home/albert/Baikal/NuEnergy/NNBlock/launcher.py", line 68, in launch_exp
    history = compile_and_train(model,
  File "/home/albert/Baikal/NuEnergy/NNBlock/train.py", line 172, in compile_and_train
    history = model.fit(train_dataset, steps_per_epoch=steps_per_epoch, epochs=input_args.num_of_epochs,
  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

2 root error(s) found.
  (0) UNKNOWN:  InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead. [Op:StridedSlice] name: strided_slice/
Traceback (most recent call last):

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1039, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 150, in __call__
    out_data = self.step(start, stop, ev_starts)

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 110, in step
    data = tf.RaggedTensor.from_row_starts(values=data, row_starts=ev_starts[0:-1] - ev_starts[0])

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead. [Op:StridedSlice] name: strided_slice/


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
  (1) UNKNOWN:  InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead. [Op:StridedSlice] name: strided_slice/
Traceback (most recent call last):

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1039, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 150, in __call__
    out_data = self.step(start, stop, ev_starts)

  File "/home/albert/Baikal/NuEnergy/NNBlock/dataset_from_h5.py", line 110, in step
    data = tf.RaggedTensor.from_row_starts(values=data, row_starts=ev_starts[0:-1] - ev_starts[0])

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/home/albert/Baikal/NuEnergy/venvNE/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1], [3], and [3] instead. [Op:StridedSlice] name: strided_slice/


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_1622045]
